language: python
python:
  - 2.7

sudo: required
dist: xenial

install:
  - pip install -r requirements.txt

script:
  - python render_devices.py
  - python -m py_compile configure_snmp.py
  
branches:
  only:
   - master

notifications:
  email:
    recipients:
      - khelil.sator.git@gmail.com
    on_failure: always
  slack: 
    ksator-junos:XAUJP6A29mgYtUtGIJQdPBS7
